version: '3'

volumes:
  redis-data:

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  
  visitor-badge:
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      - md5_key=${md5_key}
      - redis_host=redis
